Fix volume snapshotter usage of AAD URI
vmware-tanzu/velero-plugin-for-microsoft-azure pull request #256
Opened 2024-10-22 18:57 UTC by dylanbossie-rise8

Currently AAD URI will throw an error with volume snapshotter, and in practice will cause volume snapshots to be attempted using DefaultAzureCredential when used with Azure, which causes failures in certain contexts. This should resolve that issue.

2025-01-14 19:54 UTC, Jeremy-Boyle commented
@shubham-pampattiwar @ywk253100

Can you please review this if you have time, this is something that was overlooked in one of my previous commits :)

2025-01-15 06:02 UTC, kaovilai commented
I don't see it being referenced in code other than docs. can you clarify where the value of this config is used?

2025-01-23 22:17 UTC, Jeremy-Boyle requested changes
Please make these changes

2025-01-23 22:17 UTC, Jeremy-Boyle commented on velero-plugin-for-microsoft-azure/volume_snapshotter.go
> +		vslConfigKeyActiveDirectoryAuthorityURI,
@kaovilai 

Please take a look here: https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/7cc3a717566a05f4e8c7eeaf01031c77b5316835/volumesnapshotlocation.md?plain=1#L40

What happens is that when this value is specified it it will error out on the following line during its check.

Also the Readme also has information for backup locations:
https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/main/README.md#create-backup-storage-location

2025-01-23 22:17 UTC, Jeremy-Boyle commented on changelogs/unreleased/256-dylanbossie-rise8
> +Update volume_snapshotter to correctly use AAD URI which fixes behavior for Azure Workload Identities
Please remove this file @dylanbossie-rise8 , its automatically generated via commits, when a release is cut.

2025-01-23 22:19 UTC, kaovilai commented on changelogs/unreleased/256-dylanbossie-rise8
> +Update volume_snapshotter to correctly use AAD URI which fixes behavior for Azure Workload Identities
changelogs/unreleased/ is not automatically generated at least for all other velero repos.

I suggests keeping the changelog here.

2025-01-23 22:57 UTC, Jeremy-Boyle commented on changelogs/unreleased/256-dylanbossie-rise8
> +Update volume_snapshotter to correctly use AAD URI which fixes behavior for Azure Workload Identities
Ah thanks ! I didn't notice that i just looked at some other commits and MRs good job @dylanbossie-rise8 for noticing that.

2025-01-23 22:58 UTC, Jeremy-Boyle commented on changelogs/unreleased/256-dylanbossie-rise8
> +Update volume_snapshotter to correctly use AAD URI which fixes behavior for Azure Workload Identities
> changelogs/unreleased/ is not automatically generated at least for all other velero repos.
> 
> I suggests keeping the changelog here.

Ah thanks ! I didn't notice that i just looked at some other commits and MRs good job @dylanbossie-rise8 for noticing that. Side, note did you have any further questions for above ?

2025-01-24 17:33 UTC, kaovilai commented on velero-plugin-for-microsoft-azure/volume_snapshotter.go
> +		vslConfigKeyActiveDirectoryAuthorityURI,
I get the validation part. I'm trying to understand which part of the code consumes this config.

2025-01-27 16:14 UTC, Jeremy-Boyle commented on velero-plugin-for-microsoft-azure/volume_snapshotter.go
> +		vslConfigKeyActiveDirectoryAuthorityURI,
@kaovilai 

Any time config is called.

https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/7cc3a717566a05f4e8c7eeaf01031c77b5316835/velero-plugin-for-microsoft-azure/volume_snapshotter.go#L100C22-L158

Its within the azure go library, if you are looking for the specifics ?

https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/7cc3a717566a05f4e8c7eeaf01031c77b5316835/velero-plugin-for-microsoft-azure/volume_snapshotter.go#L139

Follow that chain. 

https://github.com/vmware-tanzu/velero/blob/6ac38cde8556f0fb338f1b00cd64746790b6c73c/pkg/util/azure/util.go#L82

https://github.com/vmware-tanzu/velero/blob/6ac38cde8556f0fb338f1b00cd64746790b6c73c/pkg/util/azure/util.go#L149C5-L149C33

2025-01-27 17:14 UTC, kaovilai commented on velero-plugin-for-microsoft-azure/volume_snapshotter.go
> +		vslConfigKeyActiveDirectoryAuthorityURI,
ok I see. Thanks.

2025-01-27 17:15 UTC, kaovilai approved these changes
lgtm!

2025-02-05 18:47 UTC, shubham-pampattiwar approved these changes

2025-02-05 18:47 UTC, shubham-pampattiwar commented
/cc @anshulahuja98

2025-02-06 04:45 UTC, anshulahuja98 approved these changes

2025-02-06 04:46 UTC, anshulahuja98 commented
@shubham-pampattiwar / @kaovilai  I don't seem to have access to trigger the CI
Do you folks have that?
CC: @reasonerjt

2025-02-06 05:55 UTC, shubham-pampattiwar commented
yeah me too. same access as @kaovilai

2025-02-06 16:32 UTC, Jeremy-Boyle commented
@ywk253100 @sseago 

Should be able to run the ci

2025-03-05 02:38 UTC, Jeremy-Boyle approved these changes

2025-03-05 02:45 UTC, Jeremy-Boyle commented
I just approved aswell, there is the pending requests for review , @ywk253100 @sseago when you get a chance could we have a Quick Look at this small but needed change in order for this to work?

2026-02-13 13:23 UTC, jcamu commented
Hello.

Any news on this subject ?



Thanks.

2026-07-16 15:00 UTC, kaovilai approved these changes

2026-07-16 15:38 UTC, merged